spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${DB_USERNAME}
    password: ${AZURE_PASSWORD}
    url: jdbc:postgresql://eskil4152psql.postgres.database.azure.com/eskil
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  application:
    name: people-server
  flyway:
    baseline-on-migrate: true
server:
  port: '5000'