spring:
  datasource:
    username: eskil
    url: jdbc:postgresql://localhost:5433/eskil
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  application:
    name: people-server
  flyway:
    baseline-on-migrate=true
server:
  port: '5000'